# docker-compose.yml
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,cloudformation
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - PERSISTENCE=1
    volumes:
      - "${PWD}/.localstack:/var/lib/localstack"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
